// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeIwDS4pETNlh9hMPPhCV6EOq7Rl89pTU',
    appId: '1:611668561080:web:6a5c39ecc001431151384d',
    messagingSenderId: '611668561080',
    projectId: 'dma-clinic',
    authDomain: 'dma-clinic.firebaseapp.com',
    storageBucket: 'dma-clinic.firebasestorage.app',
    measurementId: 'G-DQ4X6G7EZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnG-QkDPnFvGiI7X8QsmBPUURBmHVWtGM',
    appId: '1:611668561080:android:a7bc2e99420f2b4951384d',
    messagingSenderId: '611668561080',
    projectId: 'dma-clinic',
    storageBucket: 'dma-clinic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjHasxqow5bBcpJ__Mj_m65Ws5xFTeAGc',
    appId: '1:611668561080:ios:5547ff884f2e5f7b51384d',
    messagingSenderId: '611668561080',
    projectId: 'dma-clinic',
    storageBucket: 'dma-clinic.firebasestorage.app',
    iosClientId: '611668561080-gj96qbu6cn98ftoehm13jf6vo7u2a41i.apps.googleusercontent.com',
    iosBundleId: 'com.dma.clinic.dmaclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeIwDS4pETNlh9hMPPhCV6EOq7Rl89pTU',
    appId: '1:611668561080:web:9aab163d9332baa151384d',
    messagingSenderId: '611668561080',
    projectId: 'dma-clinic',
    authDomain: 'dma-clinic.firebaseapp.com',
    storageBucket: 'dma-clinic.firebasestorage.app',
    measurementId: 'G-VDK6PZT31X',
  );
}
